name: Update VERSION.txt

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Generate version
        run: |
          echo "v$(TZ=America/New_York date +'%Y.%m.%d-%H%M%z')-g$(git rev-parse --short HEAD)" > VERSION.txt

      - name: Conditionally commit and push version file
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Update VERSION.txt"* ]]; then
            echo "VERSION.txt already updated — skipping push to avoid loop."
          else
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add VERSION.txt
            git commit -m "Update VERSION.txt" || echo "No changes to commit"
            git push
          fi
