name: Update VERSION.txt

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Generate version
        run: |
          echo "v$(TZ=America/New_York date +'%Y.%m.%d-%H%M%z')-g$(git rev-parse --short HEAD)" > VERSION.txt

      - name: Commit and push version file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add VERSION.txt
          git commit -m "Update VERSION.txt" || echo "No changes to commit"
          git push
